language: scala

sudo: required

scala:
   - 2.12.12
   - 2.13.3

jdk:
   - openjdk8
   - openjdk11

script:
  - sbt clean scalafmtCheckAll scalafmtSbtCheck test

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt