addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"   % "0.14.8")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.12.1")
addSbtPlugin("com.github.sbt" % "sbt-header"     % "5.11.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.6.2")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"  % "2.4.4")
