addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"   % "0.14.4")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.9.3")
addSbtPlugin("com.github.sbt" % "sbt-header"     % "5.11.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.6")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"  % "2.4.2")
