addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"   % "0.9.31")
addSbtPlugin("com.github.sbt"    % "sbt-ci-release" % "1.5.11")
addSbtPlugin("de.heikoseeberger" % "sbt-header"     % "5.6.5")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.4.6")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"  % "2.0.6")
